# Desafio 5

Neste desafio, vamos praticar sobre redução de dimensionalidade com PCA e seleção de variáveis com RFE. Utilizaremos o _data set_ [Fifa 2019](https://www.kaggle.com/karangadiya/fifa19), contendo originalmente 89 variáveis de mais de 18 mil jogadores do _game_ FIFA 2019.

> Obs.: Por favor, não modifique o nome das funções de resposta.

## _Setup_ geral

In [1]:
from math import sqrt

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as sct
import seaborn as sns
import statsmodels.api as sm
import statsmodels.stats as st
from sklearn.decomposition import PCA
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [3]:
fifa = pd.read_csv("fifa.csv")

In [4]:
columns_to_drop = ["Unnamed: 0", "ID", "Name", "Photo", "Nationality", "Flag",
                   "Club", "Club Logo", "Value", "Wage", "Special", "Preferred Foot",
                   "International Reputation", "Weak Foot", "Skill Moves", "Work Rate",
                   "Body Type", "Real Face", "Position", "Jersey Number", "Joined",
                   "Loaned From", "Contract Valid Until", "Height", "Weight", "LS",
                   "ST", "RS", "LW", "LF", "CF", "RF", "RW", "LAM", "CAM", "RAM", "LM",
                   "LCM", "CM", "RCM", "RM", "LWB", "LDM", "CDM", "RDM", "RWB", "LB", "LCB",
                   "CB", "RCB", "RB", "Release Clause"
]

try:
    fifa.drop(columns_to_drop, axis=1, inplace=True)
except KeyError:
    logger.warning(f"Columns already dropped")

## Análise preliminar

In [5]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 37 columns):
Age                18207 non-null int64
Overall            18207 non-null int64
Potential          18207 non-null int64
Crossing           18159 non-null float64
Finishing          18159 non-null float64
HeadingAccuracy    18159 non-null float64
ShortPassing       18159 non-null float64
Volleys            18159 non-null float64
Dribbling          18159 non-null float64
Curve              18159 non-null float64
FKAccuracy         18159 non-null float64
LongPassing        18159 non-null float64
BallControl        18159 non-null float64
Acceleration       18159 non-null float64
SprintSpeed        18159 non-null float64
Agility            18159 non-null float64
Reactions          18159 non-null float64
Balance            18159 non-null float64
ShotPower          18159 non-null float64
Jumping            18159 non-null float64
Stamina            18159 non-null float64
Strength       

In [6]:
fifa.head()

Age  Overall  Potential  Crossing  Finishing  HeadingAccuracy  \
0   31       94         94      84.0       95.0             70.0   
1   33       94         94      84.0       94.0             89.0   
2   26       92         93      79.0       87.0             62.0   
3   27       91         93      17.0       13.0             21.0   
4   27       91         92      93.0       82.0             55.0   

   ShortPassing  Volleys  Dribbling  Curve  ...  Penalties  Composure  \
0          90.0     86.0       97.0   93.0  ...       75.0       96.0   
1          81.0     87.0       88.0   81.0  ...       85.0       95.0   
2          84.0     84.0       96.0   88.0  ...       81.0       94.0   
3          50.0     13.0       18.0   21.0  ...       40.0       68.0   
4          92.0     82.0       86.0   85.0  ...       79.0       88.0   

   Marking  StandingTackle  SlidingTackle  GKDiving  GKHandling  GKKicking  \
0     33.0            28.0           26.0       6.0        11.0       15.0   
1     28.0            31.0           23.0       7.0        11.0       15.0   
2     27.0            24.0           33.0       9.0         9.0       15.0   
3     15.0            21.0           13.0      90.0        85.0       87.0   
4     68.0            58.0           51.0      15.0        13.0        5.0   

   GKPositioning  GKReflexes  
0           14.0         8.0  
1           14.0        11.0  
2           15.0        11.0  
3           88.0        94.0  
4           10.0        13.0  

[5 rows x 37 columns]

In [7]:
nan_values = pd.DataFrame(fifa.isna().sum()/fifa.shape[0])
nan_values.columns = ['Feature']
nan_values

Feature
Age              0.000000
Overall          0.000000
Potential        0.000000
Crossing         0.002636
Finishing        0.002636
HeadingAccuracy  0.002636
ShortPassing     0.002636
Volleys          0.002636
Dribbling        0.002636
Curve            0.002636
FKAccuracy       0.002636
LongPassing      0.002636
BallControl      0.002636
Acceleration     0.002636
SprintSpeed      0.002636
Agility          0.002636
Reactions        0.002636
Balance          0.002636
ShotPower        0.002636
Jumping          0.002636
Stamina          0.002636
Strength         0.002636
LongShots        0.002636
Aggression       0.002636
Interceptions    0.002636
Positioning      0.002636
Vision           0.002636
Penalties        0.002636
Composure        0.002636
Marking          0.002636
StandingTackle   0.002636
SlidingTackle    0.002636
GKDiving         0.002636
GKHandling       0.002636
GKKicking        0.002636
GKPositioning    0.002636
GKReflexes       0.002636

Retirando observações com variáveis missing.

In [8]:
fifa = fifa[fifa['Jumping'].isna() == False]

Criando um dataset X sem a coluna 'Overall' e um dataset Y somente com esta coluna.

In [9]:
X = fifa.drop(columns=['Overall'])
Y = fifa['Overall']
fifa.shape

(18159, 37)

## Questão 1

Qual fração da variância consegue ser explicada pelo primeiro componente principal de `fifa`? Responda como um único float (entre 0 e 1) arredondado para três casas decimais.

### PCA

In [10]:
pca = PCA(n_components= 5)
pca.fit(fifa)
pca.explained_variance_ratio_

array([0.56528056, 0.18102522, 0.05952834, 0.04342693, 0.02635323])

In [11]:
def q1():
    return float(round(pca.explained_variance_ratio_[0],3))

## Questão 2

Quantos componentes principais precisamos para explicar 95% da variância total? Responda como un único escalar inteiro.

### PCA

Vale ressaltar que quando 0 < n_components < 1, o objetivo do método visa encontrar a variância declarada por n_components

In [12]:
pca = PCA(n_components=0.95)
pca.fit(fifa)
pca.explained_variance_ratio_

array([0.56528056, 0.18102522, 0.05952834, 0.04342693, 0.02635323,
       0.01207077, 0.01035505, 0.00852951, 0.00787863, 0.00720417,
       0.0071818 , 0.00632894, 0.00519242, 0.00490798, 0.00474209])

In [13]:
pca.explained_variance_ratio_.shape

(15,)

In [14]:
def q2():
    return pca.explained_variance_ratio_.shape[0]

## Questão 3

Qual são as coordenadas (primeiro e segundo componentes principais) do ponto `x` abaixo? O vetor abaixo já está centralizado. Cuidado para __não__ centralizar o vetor novamente (por exemplo, invocando `PCA.transform()` nele). Responda como uma tupla de float arredondados para três casas decimais.

In [15]:
x = [0.87747123,  -1.24990363,  -1.3191255, -36.7341814,
     -35.55091139, -37.29814417, -28.68671182, -30.90902583,
     -42.37100061, -32.17082438, -28.86315326, -22.71193348,
     -38.36945867, -20.61407566, -22.72696734, -25.50360703,
     2.16339005, -27.96657305, -33.46004736,  -5.08943224,
     -30.21994603,   3.68803348, -36.10997302, -30.86899058,
     -22.69827634, -37.95847789, -22.40090313, -30.54859849,
     -26.64827358, -19.28162344, -34.69783578, -34.6614351,
     48.38377664,  47.60840355,  45.76793876,  44.61110193,
     49.28911284
]

Utilizando os dois primeiros componentes e multiplicado-os pelo vetor x em questão, tem-se:

In [19]:
feature = pca.components_[:2]
x_np = np.array(x)
ans_q3 = feature.dot(x_np)
ans_q3

array([186.55588031,  -6.59243177])

In [20]:
def q3():
    return (round(ans_q3[0], 3), round(ans_q3[1], 3))

## Questão 4

Realiza RFE com estimador de regressão linear para selecionar cinco variáveis, eliminando uma a uma. Quais são as variáveis selecionadas? Responda como uma lista de nomes de variáveis.

Primeiro iniciamos o estimador linear.

In [21]:
linear = LinearRegression()
selector = RFE(linear, n_features_to_select= 5,step= 1)
selector.fit(X,Y)
ans_q4 = selector.support_

In [23]:
len(ans_q4)

36

In [30]:
X.columns

Index(['Age', 'Potential', 'Crossing', 'Finishing', 'HeadingAccuracy',
       'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
       'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
       'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
       'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes'],
      dtype='object')

In [52]:
var_list = []

for i in range(0,36):
    if ans_q4[i] == True:
        var_list.append(X.columns[i])
var_list

['Age', 'Potential', 'BallControl', 'Reactions', 'GKReflexes']

In [10]:
def q4():
    return var_list